# 数据源配置

spring:
  datasource:
    url: jdbc:mysql://134.175.39.56:3306/simple?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: qq123456@liangzai
    driver-class-name: com.mysql.jdbc.Driver

# MyBatis  此处在使用了maperscan后 可以不需要了/
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.example.tongji.domain
    mapper-locations: classpath:com.example.tongji.mapper/**/*.xml

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 80
  servlet:
    # 应用的访问路径
    context-path: /
